export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"
export const SET_PROFILE = "SET_PROFILE"

export const SET_VIDEOS = "SET_VIDEOS"
export const SET_POPULAR_VIDEOS = "SET_POPULAR_VIDEOS"
export const SET_RELATED_VIDEOS = "SET_RELATED_VIDEOS"
export const SET_SUBSCRIPTIONS_VIDEOS = "SET_SUBSCRIPTIONS_VIDEOS"
export const SET_VIDEOS_ERRORS = "SET_VIDEOS_ERRORS"
export const SET_VIDEO = "SET_VIDEO"


export const LIKED_VIDEOS_REQUEST = "LIKED_VIDEOS_REQUEST"
export const LIKED_VIDEOS_SUCCESS = "LIKED_VIDEOS_SUCCESS"
export const LIKED_VIDEOS_FAILED = "LIKED_VIDEOS_FAILED"

export const SET_COMMENTS = "SET_COMMENTS"
export const SET_COMMENTS_ERRORS = "SET_COMMENTS_ERRORS"


export const CREATE_COMMENT_REQUEST = "CREATE_COMMENT_REQUEST"
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS"
export const CREATE_COMMENT_FAILED = "CREATE_COMMENT_FAILED"

export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST"
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS"
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL"
export const CHANNEL_SUBSCRIPTION_STATUS = "CHANNEL_SUBSCRIPTION_STATUS"