export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGIOUT"

export const SET_VIDEOS = "SET_VIDEOS"
export const SET_POPULAR_VIDEOS = "SET_POPULAR_VIDEOS"
export const SET_RELATED_VIDEOS = "SET_RELATED_VIDEOS"
export const SET_VIDEOS_ERRORS = "SET_VIDEOS_ERRORS"
export const SET_VIDEO = "SET_VIDEO"



export const SET_COMMENTS = "SET_COMMENTS"
export const SET_COMMENTS_ERRORS = "SET_COMMENTS_ERRORS"